-- AlterTable
ALTER TABLE "Raffle" ADD COLUMN IF NOT EXISTS "artistXUrl" TEXT;
ALTER TABLE "Raffle" ADD COLUMN IF NOT EXISTS "mintPrice" TEXT;
ALTER TABLE "Raffle" ADD COLUMN IF NOT EXISTS "supply" TEXT;
